// this rest client need to install https://marketplace.visualstudio.com/items?itemName=humao.rest-client from vscode extention
@hostname = localhost
@port = {{$dotenv APP_PORT}}
@host = {{hostname}}:{{port}}
@apiKey = abcdefghijklmnopqrstuvwxyz

GET http://{{host}}/app?limit=2&page=1

###

POST http://{{host}}/app HTTP/1.1
Content-Type: application/json

{
    "key": "value 4"
}

###

PUT http://{{host}}/app/ce71181f-41d7-45c9-8b9f-c940f60ff232 HTTP/1.1
Content-Type: application/json

{
    "key": "asdf updated"
}


###

DELETE http://{{host}}/app/9da1d781-c9fc-4658-9459-0b896dfc000d HTTP/1.1

###
###
###

//-----------------------------------
//----------- With apiKey -----------
//-----------------------------------

GET http://{{host}}/app?limit=2&page=1
x-api-key: {{apiKey}}

###

POST http://{{host}}/app HTTP/1.1
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "key": "value 4"
}

###

PUT http://{{host}}/app/6ae4b4d1-1fd4-405f-b77a-9ca441483a75 HTTP/1.1
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "key": "asdf updated"
}


###

DELETE http://{{host}}/app/6ae4b4d1-1fd4-405f-b77a-9ca441483a75 HTTP/1.1
x-api-key: {{apiKey}}

###
###
###

//-----------------------------------
# ------- With apiKey + Namespace ---
//-----------------------------------

@namespace = todo

GET http://{{host}}/app/m/{{namespace}}?limit=2&page=1
x-api-key: {{apiKey}}

###

POST http://{{host}}/app/m/{{namespace}} HTTP/1.1
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "key": "value 4"
}

###

PUT http://{{host}}/app/m/{{namespace}}/6ae4b4d1-1fd4-405f-b77a-9ca441483a75 HTTP/1.1
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "key": "asdf updated"
}


###

DELETE http://{{host}}/app/m/{{namespace}}/6ae4b4d1-1fd4-405f-b77a-9ca441483a75 HTTP/1.1
x-api-key: {{apiKey}}

###
###
###